# -*- coding: utf-8 -*-

{
    'name': ' School Education Management',
    'version': '17.0.1.0.1',
    'category': 'Industries',
    'summary': """This modules helps to manage the university 
     education system""",
    'description': """This module serves as a comprehensive solution for
     efficiently managing the education system of a university enhancing
     its overall functionality and user experience.""",
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'depends': ['mail', 'hr_recruitment', 'account', 'website'],
    'data': [
        'security/education_university_management_groups.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/mail_template_data.xml',
        'wizard/application_reject_views.xml',
        'views/education_university_management_menus.xml',
        'views/res_partner_views.xml',
        'views/fee_category_views.xml',
        'views/account_journal_views.xml',
        'views/fee_types_views.xml',
        'views/fee_structure_views.xml',
        'views/account_move_views.xml',
        'views/timetable_period_views.xml',
        'views/school_exam_type_views.xml',
        'views/school_exam_views.xml',
        'views/exam_valuation_views.xml',
        'views/exam_result_views.xml',
        'views/school_timetable_views.xml',
        'views/timetable_schedule_line_views.xml',
        'views/school_application_views.xml',
        'views/school_attendace_views.xml',
        'views/school_attendance_line_views.xml',
        'views/school_student_views.xml',
        'views/school_document_type_views.xml',
        'views/school_document_views.xml',
        'views/reject_reason_views.xml',
        'views/school_course_views.xml',
        'views/school_department_views.xml',
        'views/school_subject_views.xml',
        'views/school_semester_views.xml',
        'views/school_syllabus_views.xml',
        'views/school_academic_year_views.xml',
        'views/school_batch_views.xml',
        'views/school_faculty_views.xml',
    ],
    'demo': ['demo/education_university_management_demo.xml'],
    'assets': {
        'web.assets_frontend': [
            '/mis_school_management/static/src/css/web_style.css',
            '/mis_school_management/static/src/js/online_application.js'
        ],
    },
    'images': ['static/description/schoolnew.png'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
